### ISSUE TITLE
Unset "Publishing options" if empty

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/save_draft#1]
If all the other Publishing Options are disabled for a content type and then we remove the "Published" checkbox... we should probably just remove the whole tab.

<img width="544" alt="screen shot 2016-10-24 at 9 32 24 pm" src="https://cloud.githubusercontent.com/assets/871421/19671013/612b2ef0-9a31-11e6-9eab-e90b896af133.png">

**Comment by ghost** [comment]
Made a PR that fixes this.

**Comment by laryn** [comment]
Thanks @BWPanda I just tested and it is working great!
