### ISSUE TITLE
Published content ends up with an empty "Publishing options" tab.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/save_draft#11]
Just installed save_draft on a vanilla 1.10.x Backdrop installation. I have enabled saving as draft for the *Page* content type, and created and published a page. When I edited that page, I got this:

<img width="501" alt="screen shot 2018-05-24 at 1 50 22 pm" src="https://user-images.githubusercontent.com/2423362/40463810-a0a1ddfa-5f5a-11e8-9133-4089b645025a.png">

Not sure if this belongs to core or if it should be sorted in this module. On the one hand this does not happen on a vanilla installation (because the "publish now"/"draft" options are in the form of radio buttons within the "Publishing options" tab). OTOH, no matter the situations that cause this, shouldn't core be smart enough so to be hiding empty vertical tabs? Hmmm, maybe I got this wrong.

**Comment by laryn** [comment]
Sounds like a regression. :/

https://github.com/backdrop-contrib/save_draft/issues/1

**Comment by laryn** [comment]
@klonos Which version of Save Draft were you using? I can't replicate this on my end. Unless you happened to grab 1.x-1.4.1 instead of 1.x-1.4.2, which came out a few hours later?

**Comment by laryn** [comment]
@klonos Reopen/let me know if you are still seeing this. I tested and think it's hiding the empty vertical tab correctly again.
