### ISSUE TITLE
Better submit buttons for content saving, depending on whether scheduled publication has been selected or not.

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/save_draft#6]
We should assess whether we need any tweaks now that [scheduling functionality is going into core](https://github.com/backdrop/backdrop-issues/issues/857). (e.g. if "Schedule for later" is selected, should the button say "Schedule" instead of "Publish", etc.)

**Comment by laryn** [comment]
Just tested with the 1.10 dev (to date) and with `schedule` as default on a content type we don't see the radio button options (although we do see the scheduler dates), and the submit button says "Save":

![screenshot from 2018-05-02 21-15-47](https://user-images.githubusercontent.com/871421/39557892-61285b74-4e50-11e8-9968-393c3428feac.png)

With `publish` or `draft` as the default, the view is the same except the button says "Publish":

![screenshot from 2018-05-02 21-34-51](https://user-images.githubusercontent.com/871421/39557959-c7069230-4e50-11e8-8a24-7f27506faa45.png)

I'd love feedback from any other `Save Draft` users as to what would make the most sense in adapting to the presence of the "Schedule" option here.

**Comment by herbdool** [comment]
I don't really use the module, but I'm curious how to solve this.

You'd need another button probably. Though with this third option it increases the complexity. Save Draft has "Publish" / "Save as Draft" when it's new, but when it's existing then it's "Save" / "Unpublish". With a third button you'd need to make the latter "Save" / "Unpublish" / "Unpublish and schedule". And what to do about filling in "Publish on"? There's no easy way to make it show/hide with the buttons. Are you going to show it all the time?

**Comment by laryn** [comment]
I have no idea if this is possible but what if we could do this:

- Hide the "Publish now" and "Save Draft" radio buttons, leaving "Schedule for publication" radio button visible (but the date fields hidden)
- When the "Schedule for publication" button is checked, the date fields appear and the bottom button text changes to "Schedule publication".

**Comment by oadaeh** [comment]
Probably the best way to achieve those things is to use the Form API's #states feature: https://api.backdropcms.org/form_api#states

**Comment by docwilmot** [comment]
As @laryn  said, except change the "Schedule for later" radio to a checkbox.

**Comment by klonos** [comment]
+1 to this whole thing in general, but yeah, "Schedule for publication" checkbox, changes the set of submit buttons from "Publish now"/"Save draft" to "Schedule for publication"/"Save draft".

In the second case, when user saves as draft a node with a scheduled publication date, the scheduled publication date should be saved, but the actual publication should not happen until the user edits the draft and either actually clicks the "Schedule for publication" button, or unticks the respective checkbox, and clicks on "Publish now".

**Comment by laryn** [comment]
I pushed up some further changes and am hoping someone can give me a little help (or pointer) on what remains. Here's @serundeputy's assessment (from Gitter):

> so it; looks like in save_draft you are changing the radios to a checkbox; so you'll have to do some magic in save_draft_draft_button_submit submit handler to convert that data back and save to the publish later config and prolly some more magic in the form_alter to pull in that config and set a default value for youre checkbox replacement

This conversion to a checkbox seems to be causing the problem but I'm not 100% clear on how to do what's described above (ie. "convert that data back" etc). It might work if I made this a radio but it wouldn't be very friendly since I want users to be able to deselect the scheduling option. If anyone is able to pull the latest from the `1.x-1.x-scheduler` branch and help me out, I'd appreciate it!

Current flow:

- Creating new content: if scheduling is allowed on a content type and the scheduling box is checked, hide the Publish and Draft buttons and only show Schedule and Cancel; if scheduling is not selected, show Publish, Draft and Cancel as before.
- Editing existing content: if it is published, do not show the Scheduling options/button; if it is unpublished function as above.

@klonos I'm open to the flow you described related to saving a scheduled date in draft mode but am mainly concerned with getting this functional first. And realizing that saving a future date in draft mode may mean it is a past date when you later edit it -- but that may be okay with a validation error message...

**Comment by herbdool** [comment]
Maybe you can take a shortcut, leave it as a radio and add an option to it like "Not scheduled"?

**Comment by docwilmot** [comment]
@laryn I'd see it being done like this:
- in `save_draft_form_node_form_alter()` add a checkbox element that reveals the scheduling date fields when checked, using states.
For new nodes
- add a new validate function to set `$form_state['values']['status']`: if the checkbox was ticked, then status is 2, if the "Publish" button was clicked the status is 1, if "Save draft" clicked, 0.
- use states in `save_draft_form_node_form_alter()`: if the scheduled checkbox is ticked, change the label on the "Publish" button to say "Schedule" instead and to also at the same time hide the "Save draft" button.

On edit, loading a node thats already scheduled the wording would be tricky. I'd suggest an actual string message next to the buttons saying this node is scheduled, and buttons that say "Publish" and "Save draft".

**Comment by laryn** [comment]
Closed via https://github.com/backdrop-contrib/save_draft/commit/bab85717767251072301b675ea087caa722cab9c
